# nixpacks.toml - Railway deployment configuration

[phases.setup]
nixPkgs = ["python311", "gcc", "pkg-config"]

[phases.install]
cmds = [
    "pip install --upgrade pip wheel",
    "pip install --prefer-binary --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

